name: jiva
description: "A one stop health and wellness app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  mongo_dart: ^0.10.4
  fl_chart: ^0.70.2
  intl: ^0.20.2
  http: ^1.3.0
  flutter_gemini: ^3.0.0
  speech_to_text: ^7.0.0
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  path: ^1.9.0
  table_calendar: ^3.0.9
  google_fonts:
  logger: ^2.0.2+1
  lottie: ^3.0.0
  flutter_markdown: ^0.7.6+2
  dartz:
  firebase_auth:
  cloud_firestore:
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  hive_flutter: ^1.1.0
  web_socket_channel: ^2.4.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.17
  percent_indicator: ^4.2.4
  flutter_tts: ^4.2.2
  qr_flutter: ^4.1.0
  local_auth: ^2.3.0
 
  camera: ^0.10.5+5
  heart_bpm: ^2.0.0
  torch_light: ^1.1.0
  sensors_plus: ^6.1.1
  permission_handler: ^11.4.0
  google_ml_kit: ^0.19.0
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  hive_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/anxiety.jpg
    - assets/session.jpg
    - assets/human1.jpg
    - assets/human2.jpg
    - assets/lottie/
    - assets/jiva_logo.png
